apm-server:
  host: "0.0.0.0:8200"
  auth:
    secret_token: "${APM_SECRET_TOKEN}"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"

setup.kibana:
  host: "kibana:5601"
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"
